### ISSUE TITLE
How to compile rtl version?

### ISSUE THREAD

**Issue by A-Programmer** [vkovic/uikit-computer-store-template#1]
Hello.
I'm just getting started and i dont know about npm or yarn, i know for compiling uikit can use yarn compile-rtl but i want to know how can i set rtl version of uiki in this template?

**Comment by vkovic** [comment]
You can try to set `dir="rtl"` on `html` tag in layout.

This is located at `src/templates/layouts/_index.pug`. You need to alter line 11 and set it to something like `html(lang="en" dir="rtl")`

You may alternatively check [uikit official docs about rtl support](https://getuikit.com/docs/rtl)
